---
- name: Setup Tomcat 8 Service
  hosts: all
  become: yes  # Run tasks as root
  tasks:

    - name: Copy Ubuntu 16+ systemd service file
      copy:
        src: templates/ubuntu16-svcfile.j2
        dest: /etc/systemd/system/tomcat.service
        mode: "a+x"
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 16

    - name: Reload Tomcat service config on Ubuntu 14/15
      command: update-rc.d tomcat defaults
      when: ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int < 16

    - name: Reload Tomcat service config on CentOS 6
      command: chkconfig --add tomcat
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version | int == 6

    - name: Force systemd to reload configs on Ubuntu 16+ or CentOS 7+
      systemd:
        daemon_reload: yes
      when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version | int >= 16) or
            (ansible_distribution == 'CentOS' and ansible_distribution_major_version | int >= 7)

    - name: Start & enable Tomcat 8 service
      service:
        name: tomcat
        state: started
        enabled: yes

