---
- name: Setup Tomcat 8 on Windows
  hosts: windows_servers
  gather_facts: no
  tasks:

    - name: Ensure Tomcat directory exists
      win_file:
        path: C:\Tomcat9
        state: directory

    - name: Copy Tomcat binaries
      win_copy:
        src: files/tomcat9.zip
        dest: C:\Tomcat9\tomcat9.zip

    - name: Extract Tomcat zip
      win_unzip:
        src: C:\Tomcat9\tomcat9.zip
        dest: C:\Tomcat9
        removes: C:\Tomcat9\tomcat9.zip

    - name: Update server.xml to use port 7080
      win_replace:
        path: C:\Tomcat8\conf\server.xml
        regexp: 'port="8080"'
        replace: 'port="7080"'

    - name: Ensure Tomcat service is installed and started
      win_service:
        name: Tomcat8
        start_mode: auto
        state: started
