---
- name: Setup Tomcat 8 Service on Windows
  hosts: windows_servers
  gather_facts: yes
  tasks:

    - name: Ensure Tomcat directory exists
      win_file:
        path: C:\Tomcat8
        state: directory

    - name: Copy Tomcat binaries
      win_copy:
        src: files/tomcat8.zip
        dest: C:\Tomcat8\tomcat8.zip

    - name: Extract Tomcat zip
      win_unzip:
        src: C:\Tomcat8\tomcat8.zip
        dest: C:\Tomcat8
        removes: C:\Tomcat8\tomcat8.zip

    - name: Update server.xml to use port 7080
      win_replace:
        path: C:\Tomcat8\conf\server.xml
        regexp: 'port="8080"'
        replace: 'port="7080"'

    - name: Ensure Tomcat service is installed
      win_service:
        name: Tomcat8
        start_mode: auto
        state: started
