---
- name: Deploy VPro Application
  hosts: windows_servers
  gather_facts: no
  tasks:

    - name: Copy ROOT.war to Tomcat webapps
      win_copy:
        src: files/ROOT.war
        dest: C:\Tomcat8\webapps\ROOT.war
        force: yes

    - name: Wait until ROOT directory is extracted
      win_wait_for:
        path: C:\Tomcat8\webapps\ROOT
        state: directory
        timeout: 120

  handlers:
    - name: Restart Tomcat
      win_service:
        name: Tomcat8
        state: restarted
