---
- name: Deploy VPro Application
  hosts: all
  become: yes
  tasks:

    - name: Copy ROOT.war to Tomcat webapps
      copy:
        src: artifacts/ROOT.war
        dest: /usr/local/tomcat8/webapps/ROOT.war
        owner: tomcat
        group: tomcat
        mode: '0644'
      register: deploy_info
      tags:
        - deploy

    - name: Wait until ROOT.war is extracted to ROOT directory
      wait_for:
        path: /usr/local/tomcat8/webapps/ROOT
        state: directory
        timeout: 120
      when: deploy_info.changed
      tags:
        - deploy

#    - name: Deploy web configuration file
#      template:
#        src: templates/application.j2
#        dest: /usr/local/tomcat8/webapps/ROOT/WEB-INF/classes/application.properties
#        force: yes
#      notify:
#        - Restart Tomcat
#      tags:
#        - deploy

  handlers:
    - name: Restart Tomcat
      service:
        name: tomcat
        state: restarted
